export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const FAILURE_LOGIN = 'FAILURE_LOGIN'
export const CHECK_FAILURE_LOGIN = 'CHECK_FAILURE_LOGIN'
export const INIT_CHECK_LOGIN = 'INIT_CHECK_LOGIN'

export const SUCCESS_REGISTER = 'SUCCESS_REGISTER'
export const FAILURE_REGISTER = 'FAILURE_REGISTER'
export const CHECK_FAILURE_REGISTER = 'CHECK_FAILURE_REGISTER'
export const INIT_CHECK_REGISTER = 'INIT_CHECK_REGISTER'

export const SUCCESS_FORGOT = 'SUCCESS_FORGOT'
export const FAILURE_FORGOT = 'FAILURE_FORGOT'
export const CHECK_FAILURE_FORGOT = 'CHECK_FAILURE_FORGOT'
export const INIT_CHECK_FORGOT = 'INIT_CHECK_FORGOT'

export const CAN_GET_CODE = 'CAN_GET_CODE'
export const CANNOT_GET_CODE = 'CANNOT_GET_CODE'

export const SUCCESS_GET_USERINFO = 'SUCCESS_GET_USERINFO'
export const FAILURE_GET_USERINFO = 'FAILURE_GET_USERINFO'

export const ORDERS_SUCCESS_GET = 'ORDERS_SUCCESS_GET'
export const ORDERS_SUCCESS_GET_MORE = 'ORDERS_SUCCESS_GET_MORE'
export const ORDERS_FAILURE_GET = 'ORDERS_FAILURE_GET'
export const ORDERS_MORE_GET_EMPTY = 'ORDERS_MORE_GET_EMPTY'

export const SUCCESS_GET_PRODUCT = 'SUCCESS_GET_PRODUCT'
export const SUCCESS_GET_MORE_PRODUCT = 'SUCCESS_GET_MORE_PRODUCT'
export const FAILURE_GET_PRODUCT = 'FAILURE_GET_PRODUCT'
export const MORE_GET_EMPTY_PRODUCT = 'MORE_GET_EMPTY_PRODUCT'

export const SUCCESS_GET_SUBSCRIPTION = 'SUCCESS_GET_SUBSCRIPTION'
export const SUCCESS_GET_MORE_SUBSCRIPTION = 'SUCCESS_GET_MORE_SUBSCRIPTION'
export const FAILURE_GET_SUBSCRIPTION = 'FAILURE_GET_SUBSCRIPTION'
export const MORE_GET_EMPTY_SUBSCRIPTION = 'MORE_GET_EMPTY_SUBSCRIPTION'

export const LOADING = 'LOADING'
export const LOADED = 'LOADED'